---
# tasks file for vlan
- name: Cisco NXOS - VLAN - Set
  with_items: 
    - "{{ [inventory_vlans, device_vlans] | community.general.lists_mergeby('name') }}"
  cisco.nxos.nxos_vlans:
    state: replaced
    config:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.vlan_id }}"
        state: active
