---
# tasks file for ethernet
- name: Arista EOS - Ethernet - Set Ethernet
  with_items: 
    # - "{{ inventory_snmp | ansible.builtin.combine(device_type_snmp, host_snmp, recursive=true, list_merge='append_rp') }}"
    # - "{{ device_lan_ports }}"
    # - "{{ inventory_vlans | ansible.builtin.combine(device_vlans, recursive=true, list_merge='append_rp') }}"
    - "{{ device_interfaces }}"
    - "{{ device_lag_interfaces }}"
  arista.eos.eos_interfaces:
    state: replaced
    config:
      - name: "{{ item.name }}"
        description: "{{ item.description }}"
        # mode: layer2
